package com.conciergerie.entity;
// Generated 2 juin 2026, 16:01:07 by Hibernate Tools 6.4.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name="categorie"
    ,catalog="conciergerie"
    , uniqueConstraints = @UniqueConstraint(columnNames="libelle") 
)
public class Categorie  implements java.io.Serializable {


     private int id;
     private String libelle;
     private String description;
     private String icone;
     private String couleur;
     private int delaiSlaHeures;
     private Set<Demande> demandes = new HashSet<Demande>(0);

    public Categorie() {
    }

	
    public Categorie(int id, String libelle, int delaiSlaHeures) {
        this.id = id;
        this.libelle = libelle;
        this.delaiSlaHeures = delaiSlaHeures;
    }
    public Categorie(int id, String libelle, String description, String icone, String couleur, int delaiSlaHeures, Set<Demande> demandes) {
       this.id = id;
       this.libelle = libelle;
       this.description = description;
       this.icone = icone;
       this.couleur = couleur;
       this.delaiSlaHeures = delaiSlaHeures;
       this.demandes = demandes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="libelle", unique=true, nullable=false, length=100)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="icone", length=80)
    public String getIcone() {
        return this.icone;
    }
    
    public void setIcone(String icone) {
        this.icone = icone;
    }

    
    @Column(name="couleur", length=7)
    public String getCouleur() {
        return this.couleur;
    }
    
    public void setCouleur(String couleur) {
        this.couleur = couleur;
    }

    
    @Column(name="delai_sla_heures", nullable=false)
    public int getDelaiSlaHeures() {
        return this.delaiSlaHeures;
    }
    
    public void setDelaiSlaHeures(int delaiSlaHeures) {
        this.delaiSlaHeures = delaiSlaHeures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categorie")
    public Set<Demande> getDemandes() {
        return this.demandes;
    }
    
    public void setDemandes(Set<Demande> demandes) {
        this.demandes = demandes;
    }




}


