package com.conciergerie.entity;
// Generated 2 juin 2026, 16:01:07 by Hibernate Tools 6.4.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="client"
    ,catalog="conciergerie"
    , uniqueConstraints = @UniqueConstraint(columnNames="utilisateur_id") 
)
public class Client  implements java.io.Serializable {


     private int id;
     private Utilisateur utilisateur;
     private String adresse;
     private String typeClient;
     private String batiment;
     private String etage;
     private Set<Reservation> reservations = new HashSet<Reservation>(0);
     private Set<Demande> demandes = new HashSet<Demande>(0);

    public Client() {
    }

	
    public Client(int id, Utilisateur utilisateur, String typeClient) {
        this.id = id;
        this.utilisateur = utilisateur;
        this.typeClient = typeClient;
    }
    public Client(int id, Utilisateur utilisateur, String adresse, String typeClient, String batiment, String etage, Set<Reservation> reservations, Set<Demande> demandes) {
       this.id = id;
       this.utilisateur = utilisateur;
       this.adresse = adresse;
       this.typeClient = typeClient;
       this.batiment = batiment;
       this.etage = etage;
       this.reservations = reservations;
       this.demandes = demandes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="utilisateur_id", unique=true, nullable=false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    
    @Column(name="adresse", length=255)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="type_client", nullable=false, length=11)
    public String getTypeClient() {
        return this.typeClient;
    }
    
    public void setTypeClient(String typeClient) {
        this.typeClient = typeClient;
    }

    
    @Column(name="batiment", length=100)
    public String getBatiment() {
        return this.batiment;
    }
    
    public void setBatiment(String batiment) {
        this.batiment = batiment;
    }

    
    @Column(name="etage", length=20)
    public String getEtage() {
        return this.etage;
    }
    
    public void setEtage(String etage) {
        this.etage = etage;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set<Demande> getDemandes() {
        return this.demandes;
    }
    
    public void setDemandes(Set<Demande> demandes) {
        this.demandes = demandes;
    }




}


