package com.conciergerie.entity;
// Generated 2 juin 2026, 16:01:07 by Hibernate Tools 6.4.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * Commentaire generated by hbm2java
 */
@Entity
@Table(name="commentaire"
    ,catalog="conciergerie"
)
public class Commentaire  implements java.io.Serializable {


     private int id;
     private Utilisateur utilisateur;
     private Demande demande;
     private String texte;
     private boolean interne;
     private Timestamp creeLe;

    public Commentaire() {
    }

    public Commentaire(int id, Utilisateur utilisateur, Demande demande, String texte, boolean interne, Timestamp creeLe) {
       this.id = id;
       this.utilisateur = utilisateur;
       this.demande = demande;
       this.texte = texte;
       this.interne = interne;
       this.creeLe = creeLe;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="utilisateur_id", nullable=false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="demande_id", nullable=false)
    public Demande getDemande() {
        return this.demande;
    }
    
    public void setDemande(Demande demande) {
        this.demande = demande;
    }

    
    @Column(name="texte", nullable=false, length=65535)
    public String getTexte() {
        return this.texte;
    }
    
    public void setTexte(String texte) {
        this.texte = texte;
    }

    
    @Column(name="interne", nullable=false)
    public boolean isInterne() {
        return this.interne;
    }
    
    public void setInterne(boolean interne) {
        this.interne = interne;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cree_le", nullable=false, length=19)
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }




}


