package com.conciergerie.entity;
// Generated 2 juin 2026, 16:01:07 by Hibernate Tools 6.4.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Demande generated by hbm2java
 */
@Entity
@Table(name="demande"
    ,catalog="conciergerie"
)
public class Demande  implements java.io.Serializable {


     private int id;
     private Prestataire prestataire;
     private Categorie categorie;
     private Client client;
     private String titre;
     private String description;
     private String statut;
     private String priorite;
     private Timestamp creeLe;
     private Timestamp clotureLe;
     private Set<Commentaire> commentaires = new HashSet<Commentaire>(0);
     private Set<Notation> notations = new HashSet<Notation>(0);
     private Set<PieceJointe> pieceJointes = new HashSet<PieceJointe>(0);

    public Demande() {
    }

	
    public Demande(int id, Categorie categorie, Client client, String titre, String statut, String priorite, Timestamp creeLe) {
        this.id = id;
        this.categorie = categorie;
        this.client = client;
        this.titre = titre;
        this.statut = statut;
        this.priorite = priorite;
        this.creeLe = creeLe;
    }
    public Demande(int id, Prestataire prestataire, Categorie categorie, Client client, String titre, String description, String statut, String priorite, Timestamp creeLe, Timestamp clotureLe, Set<Commentaire> commentaires, Set<Notation> notations, Set<PieceJointe> pieceJointes) {
       this.id = id;
       this.prestataire = prestataire;
       this.categorie = categorie;
       this.client = client;
       this.titre = titre;
       this.description = description;
       this.statut = statut;
       this.priorite = priorite;
       this.creeLe = creeLe;
       this.clotureLe = clotureLe;
       this.commentaires = commentaires;
       this.notations = notations;
       this.pieceJointes = pieceJointes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prestataire_id")
    public Prestataire getPrestataire() {
        return this.prestataire;
    }
    
    public void setPrestataire(Prestataire prestataire) {
        this.prestataire = prestataire;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categorie_id", nullable=false)
    public Categorie getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(Categorie categorie) {
        this.categorie = categorie;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client_id", nullable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

    
    @Column(name="titre", nullable=false, length=255)
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="statut", nullable=false, length=10)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

    
    @Column(name="priorite", nullable=false, length=7)
    public String getPriorite() {
        return this.priorite;
    }
    
    public void setPriorite(String priorite) {
        this.priorite = priorite;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cree_le", nullable=false, length=19)
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cloture_le", length=19)
    public Timestamp getClotureLe() {
        return this.clotureLe;
    }
    
    public void setClotureLe(Timestamp clotureLe) {
        this.clotureLe = clotureLe;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="demande")
    public Set<Commentaire> getCommentaires() {
        return this.commentaires;
    }
    
    public void setCommentaires(Set<Commentaire> commentaires) {
        this.commentaires = commentaires;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="demande")
    public Set<Notation> getNotations() {
        return this.notations;
    }
    
    public void setNotations(Set<Notation> notations) {
        this.notations = notations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="demande")
    public Set<PieceJointe> getPieceJointes() {
        return this.pieceJointes;
    }
    
    public void setPieceJointes(Set<PieceJointe> pieceJointes) {
        this.pieceJointes = pieceJointes;
    }




}


