package com.conciergerie.entity;
// Generated 2 juin 2026, 16:01:07 by Hibernate Tools 6.4.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Timestamp;

/**
 * Notation generated by hbm2java
 */
@Entity
@Table(name="notation"
    ,catalog="conciergerie"
    , uniqueConstraints = @UniqueConstraint(columnNames="demande_id") 
)
public class Notation  implements java.io.Serializable {


     private int id;
     private Prestataire prestataire;
     private Demande demande;
     private byte note;
     private String commentaire;
     private Timestamp creeLe;

    public Notation() {
    }

	
    public Notation(int id, Prestataire prestataire, Demande demande, byte note, Timestamp creeLe) {
        this.id = id;
        this.prestataire = prestataire;
        this.demande = demande;
        this.note = note;
        this.creeLe = creeLe;
    }
    public Notation(int id, Prestataire prestataire, Demande demande, byte note, String commentaire, Timestamp creeLe) {
       this.id = id;
       this.prestataire = prestataire;
       this.demande = demande;
       this.note = note;
       this.commentaire = commentaire;
       this.creeLe = creeLe;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prestataire_id", nullable=false)
    public Prestataire getPrestataire() {
        return this.prestataire;
    }
    
    public void setPrestataire(Prestataire prestataire) {
        this.prestataire = prestataire;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="demande_id", unique=true, nullable=false)
    public Demande getDemande() {
        return this.demande;
    }
    
    public void setDemande(Demande demande) {
        this.demande = demande;
    }

    
    @Column(name="note", nullable=false)
    public byte getNote() {
        return this.note;
    }
    
    public void setNote(byte note) {
        this.note = note;
    }

    
    @Column(name="commentaire", length=65535)
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cree_le", nullable=false, length=19)
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }




}


