package com.conciergerie.entity;
// Generated 2 juin 2026, 16:01:07 by Hibernate Tools 6.4.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name="notification"
    ,catalog="conciergerie"
)
public class Notification  implements java.io.Serializable {


     private int id;
     private Utilisateur utilisateur;
     private String type;
     private String message;
     private String lien;
     private boolean lu;
     private Timestamp creeLe;

    public Notification() {
    }

	
    public Notification(int id, Utilisateur utilisateur, String type, String message, boolean lu, Timestamp creeLe) {
        this.id = id;
        this.utilisateur = utilisateur;
        this.type = type;
        this.message = message;
        this.lu = lu;
        this.creeLe = creeLe;
    }
    public Notification(int id, Utilisateur utilisateur, String type, String message, String lien, boolean lu, Timestamp creeLe) {
       this.id = id;
       this.utilisateur = utilisateur;
       this.type = type;
       this.message = message;
       this.lien = lien;
       this.lu = lu;
       this.creeLe = creeLe;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="utilisateur_id", nullable=false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    
    @Column(name="type", nullable=false, length=60)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="message", nullable=false, length=65535)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    
    @Column(name="lien", length=255)
    public String getLien() {
        return this.lien;
    }
    
    public void setLien(String lien) {
        this.lien = lien;
    }

    
    @Column(name="lu", nullable=false)
    public boolean isLu() {
        return this.lu;
    }
    
    public void setLu(boolean lu) {
        this.lu = lu;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cree_le", nullable=false, length=19)
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }




}


