package com.conciergerie.entity;
// Generated 2 juin 2026, 16:01:07 by Hibernate Tools 6.4.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * Prestataire generated by hbm2java
 */
@Entity
@Table(name="prestataire"
    ,catalog="conciergerie"
    , uniqueConstraints = @UniqueConstraint(columnNames="utilisateur_id") 
)
public class Prestataire  implements java.io.Serializable {


     private int id;
     private Utilisateur utilisateur;
     private String zoneGeo;
     private float noteMoyenne;
     private int nbInterventions;
     private boolean disponible;
     private Set<Demande> demandes = new HashSet<Demande>(0);
     private Set<Specialite> specialites = new HashSet<Specialite>(0);
     private Set<Notation> notations = new HashSet<Notation>(0);

    public Prestataire() {
    }

	
    public Prestataire(int id, Utilisateur utilisateur, float noteMoyenne, int nbInterventions, boolean disponible) {
        this.id = id;
        this.utilisateur = utilisateur;
        this.noteMoyenne = noteMoyenne;
        this.nbInterventions = nbInterventions;
        this.disponible = disponible;
    }
    public Prestataire(int id, Utilisateur utilisateur, String zoneGeo, float noteMoyenne, int nbInterventions, boolean disponible, Set<Demande> demandes, Set<Specialite> specialites, Set<Notation> notations) {
       this.id = id;
       this.utilisateur = utilisateur;
       this.zoneGeo = zoneGeo;
       this.noteMoyenne = noteMoyenne;
       this.nbInterventions = nbInterventions;
       this.disponible = disponible;
       this.demandes = demandes;
       this.specialites = specialites;
       this.notations = notations;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="utilisateur_id", unique=true, nullable=false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    
    @Column(name="zone_geo", length=255)
    public String getZoneGeo() {
        return this.zoneGeo;
    }
    
    public void setZoneGeo(String zoneGeo) {
        this.zoneGeo = zoneGeo;
    }

    
    @Column(name="note_moyenne", nullable=false, precision=12)
    public float getNoteMoyenne() {
        return this.noteMoyenne;
    }
    
    public void setNoteMoyenne(float noteMoyenne) {
        this.noteMoyenne = noteMoyenne;
    }

    
    @Column(name="nb_interventions", nullable=false)
    public int getNbInterventions() {
        return this.nbInterventions;
    }
    
    public void setNbInterventions(int nbInterventions) {
        this.nbInterventions = nbInterventions;
    }

    
    @Column(name="disponible", nullable=false)
    public boolean isDisponible() {
        return this.disponible;
    }
    
    public void setDisponible(boolean disponible) {
        this.disponible = disponible;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prestataire")
    public Set<Demande> getDemandes() {
        return this.demandes;
    }
    
    public void setDemandes(Set<Demande> demandes) {
        this.demandes = demandes;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="prestataire_specialite", catalog="conciergerie", joinColumns = { 
        @JoinColumn(name="prestataire_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="specialite_id", nullable=false, updatable=false) })
    public Set<Specialite> getSpecialites() {
        return this.specialites;
    }
    
    public void setSpecialites(Set<Specialite> specialites) {
        this.specialites = specialites;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prestataire")
    public Set<Notation> getNotations() {
        return this.notations;
    }
    
    public void setNotations(Set<Notation> notations) {
        this.notations = notations;
    }




}


