package com.conciergerie.entity;
// Generated 2 juin 2026, 16:01:07 by Hibernate Tools 6.4.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name="reservation"
    ,catalog="conciergerie"
)
public class Reservation  implements java.io.Serializable {


     private int id;
     private Ressource ressource;
     private Client client;
     private Timestamp dateDebut;
     private Timestamp dateFin;
     private String statut;
     private String notes;

    public Reservation() {
    }

	
    public Reservation(int id, Ressource ressource, Client client, Timestamp dateDebut, Timestamp dateFin, String statut) {
        this.id = id;
        this.ressource = ressource;
        this.client = client;
        this.dateDebut = dateDebut;
        this.dateFin = dateFin;
        this.statut = statut;
    }
    public Reservation(int id, Ressource ressource, Client client, Timestamp dateDebut, Timestamp dateFin, String statut, String notes) {
       this.id = id;
       this.ressource = ressource;
       this.client = client;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.statut = statut;
       this.notes = notes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ressource_id", nullable=false)
    public Ressource getRessource() {
        return this.ressource;
    }
    
    public void setRessource(Ressource ressource) {
        this.ressource = ressource;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client_id", nullable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_debut", nullable=false, length=19)
    public Timestamp getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Timestamp dateDebut) {
        this.dateDebut = dateDebut;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_fin", nullable=false, length=19)
    public Timestamp getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Timestamp dateFin) {
        this.dateFin = dateFin;
    }

    
    @Column(name="statut", nullable=false, length=10)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

    
    @Column(name="notes", length=65535)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


