package com.conciergerie.entity;
// Generated 2 juin 2026, 16:01:07 by Hibernate Tools 6.4.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Ressource generated by hbm2java
 */
@Entity
@Table(name="ressource"
    ,catalog="conciergerie"
)
public class Ressource  implements java.io.Serializable {


     private int id;
     private String nom;
     private String typeRessource;
     private String description;
     private Integer capacite;
     private boolean actif;
     private Set<Reservation> reservations = new HashSet<Reservation>(0);

    public Ressource() {
    }

	
    public Ressource(int id, String nom, String typeRessource, boolean actif) {
        this.id = id;
        this.nom = nom;
        this.typeRessource = typeRessource;
        this.actif = actif;
    }
    public Ressource(int id, String nom, String typeRessource, String description, Integer capacite, boolean actif, Set<Reservation> reservations) {
       this.id = id;
       this.nom = nom;
       this.typeRessource = typeRessource;
       this.description = description;
       this.capacite = capacite;
       this.actif = actif;
       this.reservations = reservations;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nom", nullable=false, length=150)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="type_ressource", nullable=false, length=10)
    public String getTypeRessource() {
        return this.typeRessource;
    }
    
    public void setTypeRessource(String typeRessource) {
        this.typeRessource = typeRessource;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="capacite")
    public Integer getCapacite() {
        return this.capacite;
    }
    
    public void setCapacite(Integer capacite) {
        this.capacite = capacite;
    }

    
    @Column(name="actif", nullable=false)
    public boolean isActif() {
        return this.actif;
    }
    
    public void setActif(boolean actif) {
        this.actif = actif;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ressource")
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }




}


