package com.conciergerie.entity;
// Generated 2 juin 2026, 16:01:07 by Hibernate Tools 6.4.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * Specialite generated by hbm2java
 */
@Entity
@Table(name="specialite"
    ,catalog="conciergerie"
    , uniqueConstraints = @UniqueConstraint(columnNames="libelle") 
)
public class Specialite  implements java.io.Serializable {


     private Integer id;
     private String libelle;
     private Set<Prestataire> prestataires = new HashSet<Prestataire>(0);

    public Specialite() {
    }

	
    public Specialite(String libelle) {
        this.libelle = libelle;
    }
    public Specialite(String libelle, Set<Prestataire> prestataires) {
       this.libelle = libelle;
       this.prestataires = prestataires;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="libelle", unique=true, nullable=false, length=100)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="prestataire_specialite", catalog="conciergerie", joinColumns = { 
        @JoinColumn(name="specialite_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="prestataire_id", nullable=false, updatable=false) })
    public Set<Prestataire> getPrestataires() {
        return this.prestataires;
    }
    
    public void setPrestataires(Set<Prestataire> prestataires) {
        this.prestataires = prestataires;
    }




}


