package com.conciergerie.entity;
// Generated 2 juin 2026, 16:01:07 by Hibernate Tools 6.4.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name="utilisateur"
    ,catalog="conciergerie"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Utilisateur  implements java.io.Serializable {


     private int id;
     private String nom;
     private String prenom;
     private String email;
     private String motDePasse;
     private String role;
     private String telephone;
     private boolean actif;
     private Timestamp creeLe;
     private Set<Client> clients = new HashSet<Client>(0);
     private Set<Prestataire> prestataires = new HashSet<Prestataire>(0);
     private Set<Commentaire> commentaires = new HashSet<Commentaire>(0);
     private Set<Notification> notifications = new HashSet<Notification>(0);

    public Utilisateur() {
    }

	
    public Utilisateur(int id, String nom, String prenom, String email, String motDePasse, String role, boolean actif, Timestamp creeLe) {
        this.id = id;
        this.nom = nom;
        this.prenom = prenom;
        this.email = email;
        this.motDePasse = motDePasse;
        this.role = role;
        this.actif = actif;
        this.creeLe = creeLe;
    }
    public Utilisateur(int id, String nom, String prenom, String email, String motDePasse, String role, String telephone, boolean actif, Timestamp creeLe, Set<Client> clients, Set<Prestataire> prestataires, Set<Commentaire> commentaires, Set<Notification> notifications) {
       this.id = id;
       this.nom = nom;
       this.prenom = prenom;
       this.email = email;
       this.motDePasse = motDePasse;
       this.role = role;
       this.telephone = telephone;
       this.actif = actif;
       this.creeLe = creeLe;
       this.clients = clients;
       this.prestataires = prestataires;
       this.commentaires = commentaires;
       this.notifications = notifications;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nom", nullable=false, length=100)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", nullable=false, length=100)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="email", unique=true, nullable=false, length=255)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="mot_de_passe", nullable=false, length=255)
    public String getMotDePasse() {
        return this.motDePasse;
    }
    
    public void setMotDePasse(String motDePasse) {
        this.motDePasse = motDePasse;
    }

    
    @Column(name="role", nullable=false, length=11)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    
    @Column(name="telephone", length=20)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    
    @Column(name="actif", nullable=false)
    public boolean isActif() {
        return this.actif;
    }
    
    public void setActif(boolean actif) {
        this.actif = actif;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cree_le", nullable=false, length=19)
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="utilisateur")
    public Set<Client> getClients() {
        return this.clients;
    }
    
    public void setClients(Set<Client> clients) {
        this.clients = clients;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="utilisateur")
    public Set<Prestataire> getPrestataires() {
        return this.prestataires;
    }
    
    public void setPrestataires(Set<Prestataire> prestataires) {
        this.prestataires = prestataires;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="utilisateur")
    public Set<Commentaire> getCommentaires() {
        return this.commentaires;
    }
    
    public void setCommentaires(Set<Commentaire> commentaires) {
        this.commentaires = commentaires;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="utilisateur")
    public Set<Notification> getNotifications() {
        return this.notifications;
    }
    
    public void setNotifications(Set<Notification> notifications) {
        this.notifications = notifications;
    }




}


