hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/conciergerie?useSSL=false&serverTimezone=Europe/Paris&allowPublicKeyRetrieval=true
hibernate.connection.username=concierge_user
hibernate.connection.password=concierge_pass
